CREATE TABLE ORDER_LOG(
	SYMBOL VARCHAR(255) NOT NULL,
    DATE DATE NOT NULL,
	STRATEGY VARCHAR(255),
	PRICE_ADJ NUMERIC(10,3),
	ORDER_TYPE VARCHAR(8),
	QUANTITY BIGINT,
	COMMISION_COST NUMERIC(10,3),
	TOTAL_COST NUMERIC(14,3),
	BALANCE NUMERIC (14,2),
	PRIMARY KEY (SYMBOL, DATE)
);

-- this is the trade_log df